# Generated by Django 5.1.5 on 2025-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="/users/users_default.webp",
                help_text="Загрузите аватар",
                null=True,
                upload_to="users/",
                verbose_name="Аватар",
            ),
        ),
    ]
