# Generated by Django 5.1.5 on 2025-01-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема')),
                ('body_text', models.TextField(verbose_name='Текст письма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='ФИО')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'db_table': 'recipients',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата первой отправки')),
                ('sent_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения отправки')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('sent', 'Sent'), ('started', 'Started')], default=False, max_length=9, verbose_name='Статус отправки')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postpilot.message', verbose_name='Сообщение')),
                ('recipients', models.ManyToManyField(to='postpilot.recipient', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'mailings',
                'ordering': ['-sent_completed_at'],
            },
        ),
        migrations.CreateModel(
            name='SendAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки отправки')),
                ('status', models.CharField(choices=[('successfully', 'Successfully'), ('failed', 'Failed')], default=False, max_length=12, verbose_name='Статус отправки')),
                ('response', models.TextField(blank=True, verbose_name='Ответ сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postpilot.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка отправки',
                'verbose_name_plural': 'Попытки отправки',
                'db_table': 'send_attempts',
                'ordering': ['-attempt_at'],
            },
        ),
    ]
