# Generated by Django 5.1.5 on 2025-02-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postpilot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("sent", "Sent"),
                    ("started", "Started"),
                ],
                default="completed",
                max_length=9,
                verbose_name="Статус отправки",
            ),
        ),
        migrations.AlterField(
            model_name="recipient",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="ФИО"),
        ),
    ]
