# Generated by Django 5.1.5 on 2025-02-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postpilot", "0002_alter_mailing_status_alter_recipient_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("completed", "Completed"), ("created", "Created"), ("started", "Started")],
                default="created",
                max_length=9,
                verbose_name="Статус отправки",
            ),
        ),
    ]
