# Generated by Django 5.1.5 on 2025-03-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postpilot", "0006_mailing_owner_message_owner_recipient_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["-sent_completed_at"],
                "permissions": [("disable_mailing", "Can disable mailings")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
